logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
spring:
  messages:
    basename: i18n/messages

---
app:
  constants:
    awsMessageIdKeyName: awsMessageId
    awsMailContentCharset: UTF-8